### ISSUE TITLE
[Bug] Youtube Error 404 monkey appears in iridium settings

### ISSUE THREAD

**Issue by Nallat** [ParticleCore/Iridium#324]
Browser Name: Google Chrome

Browser Version: 64.0.3282.140

Operating System: Windows 10 Fall Creators Update Build 16299

Software Type: WebExtension

Software Version: v0.0.2

Here's the proof that I'm not using vivaldi.
https://imgur.com/a/kuGYG

And what you asked for:
![1](https://user-images.githubusercontent.com/36114925/35771457-8a66ea90-092d-11e8-89e8-ecf8524dcfe6.png)
![2](https://user-images.githubusercontent.com/36114925/35771458-8a81353a-092d-11e8-935f-326d76befd04.png)

@ParticleCore I'm rather disappointed that you blocked me for a misunderstanding, I didn't have the time to properly justify myself, yes I installed ghostery and qwant on chrome I didn't have it before because I just installed chrome, I installed it just after. To take screenshot I use Snagit it automatically selects the interior of the window,I selected the whole screen just now to prove that I was using chrome, I just forgot to do it the second time.

**Comment by ParticleCore** [comment]
I understand, for that reason I apologize. Whatever is happening on your browser is something that should be impossible and I can only blame it on either on something that is wrong on your browser or an extension that is causing it.

Please try it again with all extensions disabled and only Iridium installed. And don't use the Firefox extension, use the proper Chrome extension instead: https://chrome.google.com/webstore/detail/iridium/gbjmgndncjkjfcnpfhgidhbgokofegbl

The console is showing two body element tags, that should not be happening.

**Comment by NallatRebord** [comment]
@ParticleCore I just reinstalled Chrome, I don't have any other extension and yet the issue is still there
![g](https://user-images.githubusercontent.com/36114925/35771636-7b4c5fa6-0930-11e8-9d60-fee231022a3b.png)

**Comment by NallatRebord** [comment]
@ParticleCore I tested on firefox the issue is not present, tomorrow I'm going to test chromium on another pc or a virtual machine to see if the problem is personal.

**Comment by ParticleCore** [comment]
I have tested on 3 different machines, that never happens on my end, no matter how many times I try to repeat your steps in the video.

When you test again, test on Chrome with the userscript version + Tampermonkey, remember to disable the extension version so that you don't have 2 Iridium running at the same time.

At least knowing that this does not happen on Firefox is a good thing, it might mean this is restricted to Chrome only, but for what reason is a total mystery to me.

Again, sorry for what happened before and I appreciate your help.

**Comment by ParticleCore** [comment]
I have a feeling that the only explanation might be related to this hypotesis, but you have to do something first when you have the chance:

With the same empty Chrome just with the Iridium extension version and nothing else, open `chrome://apps/` in a new tab and delete the YouTube app.  
Close Chrome and open it again, see if the settings problem is still there.

**Comment by NallatRebord** [comment]
@ParticleCore I've tested everything you said nothing works. I'm going to go to bed, in france it's late.

**Comment by ParticleCore** [comment]
I am sad to hear that it didn't work and thanks for giving one last try before going. In that case I cannot think of anything else other than to hide the iframe, which is mostly a patch than a fix, but it will have to do.

However, the change will not be applied to the extension versions until a new update is released, this means that until then only userscripts will receive this sooner, which you will be able to refresh by pressing the `Ctrl` + `Shift + `R` tomorrow.

**Comment by NallatRebord** [comment]
@ParticleCore I don't have this problem anymore with userscript but I still have it with the extension, I tested it with a virtual machine and I didn't manage to get the bug.

**Comment by ParticleCore** [comment]
That is because I am now hiding any iframe that might be present in the settings page, but only the userscript can download the latest CSS file on its own, the extensions will be pending an update to get this change as well.

Seeing that the userscript appears to show this problem as fixed I'm going to mark this one as bug and ship the fix to the extension versions with the next update.

Thanks for the help, Nallat

**Comment by Nallat** [comment]
@ParticleCore I still have this bug on version 0.0.4 of Iridium, on the userscript version and the extension

http://sendvid.com/kx3smi8t

The only solution I found was to add youtube.com##iframe to my ad blocker.

**Comment by ParticleCore** [comment]
@Nallat I am sorry to hear that, the fix got removed with the update:

https://github.com/ParticleCore/Iridium/commit/ddcd3f3fb8e4f2f67367e6e5071368e041658418#diff-bf7b9c044c58a4e1c3e722603b90af1dL764

I'm going to post it again at once.

**Comment by ParticleCore** [comment]
@Nallat It should now be fixed, finally-

**Comment by Nallat** [comment]
@ParticleCore I still have the bug on v0.0.5 (only userscript)
https://imgur.com/a/mdlRu

**Comment by ParticleCore** [comment]
Try again, the CSS fix was not applied to the GitHub distribution by mistake. This has to be the worst attempt at fixing something I've ever done, I am really sorry for all that happened since start.

**Comment by TankedThomas** [comment]
I'm having the same issue with the user script version (up-to-date) on Safari (Version 11.0.3 (13604.5.6)) on macOS 10.13.3. The icon doesn't appear either (and I'm in the material design layout).
