### ISSUE TITLE
Full Browser Feature

### ISSUE THREAD

**Issue by frightener-boy** [ParticleCore/Iridium#546]
When i try to use the feature the players goes full browser as intended however the video is shown on the top left of my screen
<img width="960" alt="sans titre" src="https://user-images.githubusercontent.com/36320460/44223021-b5a55100-a186-11e8-9768-70dabd40313d.png">

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by LazyBoot** [comment]
I was having this issue as well, but today it's gone. I'm assuming it was fixed in update 0.2.1.

**Comment by ParticleCore** [comment]
@LazyBoot The recent update does address this issue, but it is possible that it might not have fixed it for everyone since YouTube does phased website changes, so some users might still have the "unbroken" version of YouTube that is now broken with the new Iridium update.

**Comment by ParticleCore** [comment]
Closing this for now, if you still have any issues follow the instructions in my previous reply.
